name: flutter_tech_task
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.6"

dependencies:
  flutter:
    sdk: flutter
  http: "1.6.0"

  cupertino_icons: "1.0.8"
  flutter_bloc: "9.1.1"
  equatable: "2.0.8"
  get_it: "9.2.0"
  rxdart: "0.28.0"
  objectbox: "5.1.0"
  objectbox_flutter_libs: "5.1.0"
  objectbox_generator: "5.1.0"
  path_provider: "2.1.5"
  path: "1.9.1"

dev_dependencies:
  build_runner: "2.10.5"
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: "6.0.0"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/posts.json
    - assets/post_details_1.json
    - assets/post_details_2.json
    - assets/post_details_3.json
    - assets/post_comments_1.json

  uses-material-design: true
